project:
  type: website
  execute-dir: project
  render:
    - "*.qmd"
execute:
  eval: false      # Add this
  freeze: true
  cache: true
website:
  title: "blog"
  navbar:
    right:
      - text: "Projects"
        href: projects.qmd
      - about.qmd
      - icon: github
        href: https://github.com/sevigti
      - icon: twitter
        href: https://x.com/elvis_visi23
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    page-layout: full
    fontsize: 1.1em
    linestretch: 1.7
    link-external-newwindow: true